### ISSUE TITLE
A couple of question to adapt the wiring order to my clock

### ISSUE THREAD

**Issue by nioubo** [Winston-Lu/ESP8266-LED-Shelf#14]
Hi, 

Currently, my clock is heavily wired from DIY Machines template method, but mine is upscaled a bit, it uses 14 LED a segement, with a total of 392 LED, I also assigned a dedicated PIN for the two dots clock separator "HH : MM".

Downside: I am trying to adapt your code to mine, but I fail at the point of even with the 12 or 24 Hours layout i cannot figure out how to remap because I dont use LED spacer between the digits.

I also use a ESP8266.

I am attaching you a picture from my clock version... Starting point : Middle right. (from picture)

Many thanks for any help.

![20231129_141736](https://github.com/Winston-Lu/ESP8266-LED-Shelf/assets/99299236/65a2b9a4-dea8-4a41-bc3b-a9d62a0433e8)

**Comment by Winston-Lu** [comment]
You should be able in `Config.h` to configure the segment wiring order. You can comment out the hyphen segment and if it causes compile errors, any code that references that constant. The code should work without any leds between digits, you’ll just need to completely reconfigure the relevant lines in the configuration file. You will need to uncomment the 24 hour layout and then reconfigure which segments correspond to which segment on each digit. If you could annotate in your picture the direction your LEDs are wired in, I can help create a `Config.h` for your setup when I have time later this week

**Comment by nioubo** [comment]
I totally understand that your project is initally about your clock version, that's alright for me. (for the extras effects part.)

24 hours part uncommented.

but it's a pain for me to understand how to remap the segment, I am not a programmer myself so it's hard to understand everything in the code. I did an update from my picture according to your wish with the wiring order. Thank you again for your kind help
![schematic](https://github.com/Winston-Lu/ESP8266-LED-Shelf/assets/99299236/6a8bf38f-1e91-473c-aeba-baecb5d53dd5)

**Comment by nioubo** [comment]
Just a quick update, I tried myself to update some parts of the code, but I don't know if it is correct... I wonder if I shall continue to rewrite your code or it is useless ?

Here is basically my segment wiring order :
![segment_wiring_order](https://github.com/Winston-Lu/ESP8266-LED-Shelf/assets/99299236/2af5fd37-e1c2-4aa6-9b58-80154a9794ec)


And below the Config.h file I am working on. Lines between 86 to 97

> #ifdef _24_HR_CLOCK
>  //1-indexed
>  const int PROGMEM segmentWiringOrder[] = {-8,1,9,-16,23,31,-24,17,-10,-2,3,11,-18,25,-32,33,-26,19,-12,-4,5,13,-20,27,-34,35,-28,21,-14,-6,7,15,-22,29,-36,37,-30}; 
>  const int PROGMEM spotlightWiringOrder[] = {0,1,2,3,4,5,6,7,8};
>  //0-indexed
>  //const int PROGMEM hyphenSegment = 18;
>  //indexes of the digits (0-indexed)
>  const int PROGMEM m_one[] = {1,2,3,4,5,6,7}; 
>  const int PROGMEM m_ten[] = {8,9,10,11,12,13,14};
>  const int PROGMEM h_one[] = {15,16,17,18,19,20,21};
>  const int PROGMEM h_ten[] = {22,23,24,25,26,27,28};
>#endif

**Comment by Winston-Lu** [comment]
Ill get back to this likely sometime later this week since Im pretty busy, but the segment order for the ones should be like 2 3 1 4 7 5 6 for the minutes ones. For the segment order Id put a 0 for the segments you dont have, so it should be like 23 0 16 0 9 0 2 24 22 17 15 10 and so on, with negatives if the segment is wired in the right to left direction or bottom to top direction. I am also abroad so I wont have access to my shelf to test so this is all the help I can provide on my phone for now. If you still run into issues let me know since Im not sure if the code will handle 0 segments without crashing

**Comment by Winston-Lu** [comment]
Give this config a try and let me know if it works or not:
Line 6:
```c++
#define LEDS_PER_LINE 14
```
Line 14-16:
```c++
//Clock format
//#define _12_HR_CLOCK
#define _24_HR_CLOCK
```
Line 86-97:
```c++
#ifdef _24_HR_CLOCK
  //1-indexed
  const int PROGMEM segmentWiringOrder[] = {-23, 0, -16, 0, -9, 0, -2, 24, -22, -17, 15, -10, 8, -3, 1, 25, 0, 18, 0, 11, 0, 4, -28, 26, -21, 29, -14, 12, -7, 5, -27, 0, -20, 0, -13, 0, 6}; 
  const int PROGMEM spotlightWiringOrder[] = {0,1,2,3,4,5,6,13,12,11,10,9,8,7};
  //0-indexed
  //const int PROGMEM hyphenSegment = 18;
  //indexes of the digits (0-indexed)
  const int PROGMEM m_one[] = {6,13,14,21,28,29,36}; 
  const int PROGMEM m_ten[] = {4,11,12,19,26,27,34};
  const int PROGMEM h_one[] = {2,9,10,17,24,25,32};
  const int PROGMEM h_ten[] = {0,7,8,15,22,23,30};
#endif
```
If any of the segments display backwards, try adding or removing the negative sign on the repective number in `segmentWiringOrder` 

I'll push some changes to the code to support 0 indexes in segmentWiringOrder to note that those segments dont exist

**Comment by nioubo** [comment]
I am sorry but I will need more time, 

I've beed tested positive a second time for the covid19, I cannot do anything rightnow, i am feeling mentally and physically like a zombie right now.

Once I can do thoses tests I will report you back with the results.

**Comment by nioubo** [comment]
I guess I got the same problem as #6 

https://github.com/Winston-Lu/ESP8266-LED-Shelf/assets/99299236/5fecb690-a408-4eca-8dd2-9ef043178370

I do not know if it's the issue, but DIYMachines recommended a GPIO pin with a PWM feature, afaik, NodeMCU 8266 has PWM but software, so not hardware (?)

**Comment by Winston-Lu** [comment]
Dont think its a pin issue since the issue mentioned in #6 only affects the first led in the strip. I may have to do some further debugging with this since I think its having issues translating the LED strip segment to the proper LED. Did you update`Lighting.cpp` to the latest version I pushed yesterday?

**Comment by nioubo** [comment]
Yes, I used the "Download whole Zip" function yesterday, I removed (commenting out) the Hyphensegment before uploading the video.

**Comment by Winston-Lu** [comment]
It seems like the loop animation is more broken than usual and would play until it connects to your wifi network. I’ll try to write some debug code for you to run at a later date when I have some more time when I have access to a PC

**Comment by Winston-Lu** [comment]
I apologize for the inactivity here, I will return to this project around early January once I get moved and settled in, hopefully you feel better by then and I can have some code for you to run and debug

**Comment by nioubo** [comment]
Don't worry, but don't recode more your script right now. I don't know where to start the debug process... I feel dumb because some (all?) of my leds are broken, even with an Arduino nano with a simple Rainbow snippet from FastLED it isn't working as expected...  I will need some time to order again a LED strip on Aliexpress next month.

If you wish you can close this issue and I will re-open it in a few months, if it's ok for you.

**Comment by Winston-Lu** [comment]
Maybe try a series resistor between the data pin on the esp and the dat pin on the led strip. I’ll keep this thread open for now since it is still ongoing

**Comment by nioubo** [comment]
Sorry for the late response. We can close this issue.

I've rebuilt the clock using your template with my upscaled models.
Right now I wired only the hours and it works great ! Thanks you very much

![photo_2024-04-04_17-39-31](https://github.com/Winston-Lu/ESP8266-LED-Shelf/assets/99299236/a3a65d2c-28e6-42a7-ba86-7b90b3d5b8be)
