### ISSUE TITLE
Clock keeps rebooting

### ISSUE THREAD

**Issue by DVEntertainment** [Winston-Lu/ESP8266-LED-Shelf#15]
Hi!

Today i tried adjusting the utc offset to compensate for daylightsaving. After this the clock keeps rebooting. It gives the "connecting to network" signalling, then the clock shows but in the background i still see it circling. Then it goes off and on again, trying to connect again. If i'm lucky i can connect to the webpage but it fails to load often. I tried reinstalling the software, tried a different wifi accespoint, different NTP server and i have no idea why it is broken now. next step would be a new ESP. Do you have any idea what it could be? It worked flawelessly for over 2 years

With regards,
Daniël

**Comment by Winston-Lu** [comment]
I did have issues with my device where the webpage does not load completely or loads very slowly after long uptimes (usually after several weeks/months). Usually a reboot works for me, but I havent had much issues with the Wi-Fi being unable to connect. See if you can get an example ESP8266 WiFi sketch uploaded and connected to your network access point. I'm not 100% what could be the issue, its possible that the EEPROM emulation may have finally run its course. Let me know if you can get an example sketch working and connected and we can see what to try from there

**Comment by DVEntertainment** [comment]
It probably was the EEPROM indeed. A new ESP8266 did fix the problem! Now i cant access my webpage anymore, prlly a config error on my side. but since i use the http requests anyway that isnt a big deal for me. Now i can finally continue to enjoy your work every day :)
