### ISSUE TITLE
IDEA: Timer

### ISSUE THREAD

**Issue by DVEntertainment** [Winston-Lu/ESP8266-LED-Shelf#8]
Hi!

Could you maybe add some timerfeature? (at 6:00 turn clock brightness up, at 8:00 turn it to office colors, at 20:00 turn it to moody at 23:00 dim the clock).

Or could you make it google home enabled? That would solve the same problem.

thanx!

**Comment by Winston-Lu** [comment]
Im not quite sure how to implement Google Home onto the ESP8266, but implementing an effect scheduler based on time shouldn't be too difficult with the current functions/features. I'll work on it soon and provide a template to customize

**Comment by Winston-Lu** [comment]
I've pushed a commit to master for this feature. Let me know if there are any bugs or if you have any questions on configuration. To enable the feature, you should go to the webserver this creates, and in the "Commands" section, type `effecttimer 1`. Right now, I have an example for a setup for a 00:00 -> 06:00 setup, which you should be able to use as a template for other time-related effects
